name: Build Messenger Neo

on:
  push:
    branches: [ main, master, canary ]
  pull_request:
    branches: [ main, master, canary ]
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build macOS (Apple Silicon & Intel)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build -- --mac

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mac-artifacts
          path: |
            dist/*.dmg
            dist/*.zip
            dist/latest-mac.yml

  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Windows
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build -- --win

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: win-artifacts
          path: |
            dist/*.exe
            dist/latest.yml

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Linux
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build -- --linux

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-artifacts
          path: |
            dist/*.AppImage
            dist/latest-linux.yml
